version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
